env:
  es6: true
  browser: true
  commonjs: true
  jasmine: true
  jest: true

extends: ['htmlacademy/es6',
          'prettier/@typescript-eslint',
          'plugin:react/recommended',
          ]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

rules:
  prettier/prettier:
    ['error',
    'singleQuote': true,
    'space-in-brackets': 'never'
    ]

plugins: ['react', '@typescript-eslint', 'prettier']

settings:
  react:
    version: '16'

parser: '@typescript-eslint/parser'
