env:
  es6: true
  browser: true
  commonjs: true
  jasmine: true
  jest: true

extends: ['htmlacademy/es6',
          'plugin:react/recommended',
          'eslint:recommended',
          'plugin:react/recommended',
          'plugin:@typescript-eslint/recommended',
          'prettier/@typescript-eslint',
          'plugin:prettier/recommended'
          ]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

rules:
  prettier/prettier:
    ['error',
    'singleQuote': true
    ]

plugins: ['react', '@typescript-eslint', 'prettier']

settings:
  react:
    version: '16'
    pragma: React,
    version: detect

parser: [@typescript-eslint/parser]
